import { City } from '../types';

export const INDONESIAN_CITIES: City[] = [
  // --- DKI JAKARTA & BANTEN ---
  { id: 'jkt', name: 'DKI Jakarta', province: 'DKI Jakarta', latitude: -6.2088, longitude: 106.8456, timezone: 'WIB' },
  { id: 'srg', name: 'Serang', province: 'Banten', latitude: -6.12, longitude: 106.15, timezone: 'WIB' },
  { id: 'tgr', name: 'Tangerang (Kota)', province: 'Banten', latitude: -6.1783, longitude: 106.6319, timezone: 'WIB' },
  { id: 'tgs', name: 'Tangerang Selatan', province: 'Banten', latitude: -6.2889, longitude: 106.7181, timezone: 'WIB' },
  { id: 'clg', name: 'Cilegon', province: 'Banten', latitude: -6.0028, longitude: 106.0125, timezone: 'WIB' },
  { id: 'k-lbg', name: 'Lebak (Rangkasbitung)', province: 'Banten', latitude: -6.3625, longitude: 106.2528, timezone: 'WIB' },
  { id: 'k-pdg', name: 'Pandeglang', province: 'Banten', latitude: -6.3083, longitude: 106.1069, timezone: 'WIB' },

  // --- JAWA BARAT (Lengkap Kota & Kabupaten) ---
  { id: 'bdg', name: 'Bandung (Kota)', province: 'Jawa Barat', latitude: -6.9175, longitude: 107.6191, timezone: 'WIB' },
  { id: 'k-bdg', name: 'Kabupaten Bandung (Soreang)', province: 'Jawa Barat', latitude: -7.0252, longitude: 107.5198, timezone: 'WIB' },
  { id: 'k-kbb', name: 'Kabupaten Bandung Barat (Ngamprah)', province: 'Jawa Barat', latitude: -6.8439, longitude: 107.5028, timezone: 'WIB' },
  { id: 'cmh', name: 'Cimahi', province: 'Jawa Barat', latitude: -6.8723, longitude: 107.5432, timezone: 'WIB' },
  { id: 'bgr', name: 'Bogor (Kota)', province: 'Jawa Barat', latitude: -6.5971, longitude: 106.806, timezone: 'WIB' },
  { id: 'k-bgr', name: 'Kabupaten Bogor (Cibinong)', province: 'Jawa Barat', latitude: -6.4839, longitude: 106.8524, timezone: 'WIB' },
  { id: 'dpk', name: 'Depok', province: 'Jawa Barat', latitude: -6.4025, longitude: 106.7942, timezone: 'WIB' },
  { id: 'bks', name: 'Bekasi (Kota)', province: 'Jawa Barat', latitude: -6.2383, longitude: 106.9756, timezone: 'WIB' },
  { id: 'k-bks', name: 'Kabupaten Bekasi (Cikarang)', province: 'Jawa Barat', latitude: -6.2974, longitude: 107.1706, timezone: 'WIB' },
  { id: 'skb', name: 'Sukabumi (Kota)', province: 'Jawa Barat', latitude: -6.9277, longitude: 106.9298, timezone: 'WIB' },
  { id: 'k-skb', name: 'Kabupaten Sukabumi (Pelabuhan Ratu)', province: 'Jawa Barat', latitude: -6.9875, longitude: 106.5411, timezone: 'WIB' },
  { id: 'cjr', name: 'Cianjur', province: 'Jawa Barat', latitude: -6.8172, longitude: 107.1397, timezone: 'WIB' },
  { id: 'pwk', name: 'Purwakarta', province: 'Jawa Barat', latitude: -6.5569, longitude: 107.4433, timezone: 'WIB' },
  { id: 'krw', name: 'Karawang', province: 'Jawa Barat', latitude: -6.3073, longitude: 107.3074, timezone: 'WIB' },
  { id: 'sbg', name: 'Subang', province: 'Jawa Barat', latitude: -6.5716, longitude: 107.7587, timezone: 'WIB' },
  { id: 'crb', name: 'Cirebon (Kota)', province: 'Jawa Barat', latitude: -6.732, longitude: 108.5523, timezone: 'WIB' },
  { id: 'k-crb', name: 'Kabupaten Cirebon (Sumber)', province: 'Jawa Barat', latitude: -6.7628, longitude: 108.4839, timezone: 'WIB' },
  { id: 'kng', name: 'Kuningan', province: 'Jawa Barat', latitude: -6.9767, longitude: 108.4833, timezone: 'WIB' },
  { id: 'mjl', name: 'Majalengka', province: 'Jawa Barat', latitude: -6.8361, longitude: 108.2278, timezone: 'WIB' },
  { id: 'smd', name: 'Sumedang', province: 'Jawa Barat', latitude: -6.8586, longitude: 107.9197, timezone: 'WIB' },
  { id: 'idm', name: 'Indramayu', province: 'Jawa Barat', latitude: -6.3264, longitude: 108.32, timezone: 'WIB' },
  { id: 'grt', name: 'Garut', province: 'Jawa Barat', latitude: -7.2167, longitude: 107.9, timezone: 'WIB' },
  { id: 'tsm', name: 'Tasikmalaya (Kota)', province: 'Jawa Barat', latitude: -7.3274, longitude: 108.2207, timezone: 'WIB' },
  { id: 'k-tsm', name: 'Kabupaten Tasikmalaya (Singaparna)', province: 'Jawa Barat', latitude: -7.3512, longitude: 108.1127, timezone: 'WIB' },
  { id: 'cms', name: 'Ciamis', province: 'Jawa Barat', latitude: -7.3267, longitude: 108.3541, timezone: 'WIB' },
  { id: 'bjr', name: 'Banjar', province: 'Jawa Barat', latitude: -7.3697, longitude: 108.5332, timezone: 'WIB' },
  { id: 'pnd', name: 'Pangandaran', province: 'Jawa Barat', latitude: -7.7011, longitude: 108.4947, timezone: 'WIB' },

  // --- JAWA TENGAH (Lengkap Kota & Kabupaten) ---
  { id: 'smg', name: 'Semarang (Kota)', province: 'Jawa Tengah', latitude: -6.9667, longitude: 110.4167, timezone: 'WIB' },
  { id: 'k-smg', name: 'Kabupaten Semarang (Ungaran)', province: 'Jawa Tengah', latitude: -7.1394, longitude: 110.4042, timezone: 'WIB' },
  { id: 'slo', name: 'Surakarta (Solo)', province: 'Jawa Tengah', latitude: -7.5755, longitude: 110.8243, timezone: 'WIB' },
  { id: 'slt', name: 'Salatiga', province: 'Jawa Tengah', latitude: -7.3305, longitude: 110.5084, timezone: 'WIB' },
  { id: 'mgl', name: 'Magelang (Kota)', province: 'Jawa Tengah', latitude: -7.4706, longitude: 110.2178, timezone: 'WIB' },
  { id: 'k-mgl', name: 'Kabupaten Magelang (Mungkid)', province: 'Jawa Tengah', latitude: -7.575, longitude: 110.2319, timezone: 'WIB' },
  { id: 'pkl', name: 'Pekalongan (Kota)', province: 'Jawa Tengah', latitude: -6.8886, longitude: 109.6753, timezone: 'WIB' },
  { id: 'k-pkl', name: 'Kabupaten Pekalongan (Kajen)', province: 'Jawa Tengah', latitude: -7.0289, longitude: 109.5892, timezone: 'WIB' },
  { id: 'tgl', name: 'Tegal (Kota)', province: 'Jawa Tengah', latitude: -6.8694, longitude: 109.1402, timezone: 'WIB' },
  { id: 'k-tgl', name: 'Kabupaten Tegal (Slawi)', province: 'Jawa Tengah', latitude: -6.9856, longitude: 109.1381, timezone: 'WIB' },
  { id: 'pwt', name: 'Purwokerto (Banyumas)', province: 'Jawa Tengah', latitude: -7.4244, longitude: 109.2303, timezone: 'WIB' },
  { id: 'clp', name: 'Cilacap', province: 'Jawa Tengah', latitude: -7.7279, longitude: 109.0059, timezone: 'WIB' },
  { id: 'pbg', name: 'Purbalingga', province: 'Jawa Tengah', latitude: -7.3889, longitude: 109.3639, timezone: 'WIB' },
  { id: 'bjn', name: 'Banjarnegara', province: 'Jawa Tengah', latitude: -7.3972, longitude: 109.6972, timezone: 'WIB' },
  { id: 'kbm', name: 'Kebumen', province: 'Jawa Tengah', latitude: -7.6697, longitude: 109.6522, timezone: 'WIB' },
  { id: 'pwr', name: 'Purworejo', province: 'Jawa Tengah', latitude: -7.7144, longitude: 110.0094, timezone: 'WIB' },
  { id: 'wsb', name: 'Wonosobo', province: 'Jawa Tengah', latitude: -7.3639, longitude: 109.9, timezone: 'WIB' },
  { id: 'byl', name: 'Boyolali', province: 'Jawa Tengah', latitude: -7.5333, longitude: 110.5967, timezone: 'WIB' },
  { id: 'klt', name: 'Klaten', province: 'Jawa Tengah', latitude: -7.7056, longitude: 110.6042, timezone: 'WIB' },
  { id: 'skh', name: 'Sukoharjo', province: 'Jawa Tengah', latitude: -7.6833, longitude: 110.8333, timezone: 'WIB' },
  { id: 'wng', name: 'Wonogiri', province: 'Jawa Tengah', latitude: -7.8167, longitude: 110.925, timezone: 'WIB' },
  { id: 'kra', name: 'Karanganyar', province: 'Jawa Tengah', latitude: -7.5964, longitude: 110.9508, timezone: 'WIB' },
  { id: 'srg-jt', name: 'Sragen', province: 'Jawa Tengah', latitude: -7.4264, longitude: 111.0222, timezone: 'WIB' },
  { id: 'pwd', name: 'Grobogan (Purwodadi)', province: 'Jawa Tengah', latitude: -7.0869, longitude: 110.9169, timezone: 'WIB' },
  { id: 'blr', name: 'Blora', province: 'Jawa Tengah', latitude: -6.9697, longitude: 111.4186, timezone: 'WIB' },
  { id: 'rbg', name: 'Rembang', province: 'Jawa Tengah', latitude: -6.7083, longitude: 111.3417, timezone: 'WIB' },
  { id: 'pti', name: 'Pati', province: 'Jawa Tengah', latitude: -6.7558, longitude: 111.0381, timezone: 'WIB' },
  { id: 'kds', name: 'Kudus', province: 'Jawa Tengah', latitude: -6.8047, longitude: 110.8406, timezone: 'WIB' },
  { id: 'jpr-jt', name: 'Jepara', province: 'Jawa Tengah', latitude: -6.5928, longitude: 110.6778, timezone: 'WIB' },
  { id: 'dmk', name: 'Demak', province: 'Jawa Tengah', latitude: -6.8944, longitude: 110.6389, timezone: 'WIB' },
  { id: 'tmg', name: 'Temanggung', province: 'Jawa Tengah', latitude: -7.3167, longitude: 110.1667, timezone: 'WIB' },
  { id: 'kdl', name: 'Kendal', province: 'Jawa Tengah', latitude: -6.9208, longitude: 110.2033, timezone: 'WIB' },
  { id: 'btg', name: 'Batang', province: 'Jawa Tengah', latitude: -6.9086, longitude: 109.7314, timezone: 'WIB' },
  { id: 'pml', name: 'Pemalang', province: 'Jawa Tengah', latitude: -6.8906, longitude: 109.3808, timezone: 'WIB' },
  { id: 'bbs', name: 'Brebes', province: 'Jawa Tengah', latitude: -6.8708, longitude: 109.0417, timezone: 'WIB' },

  // --- DI YOGYAKARTA ---
  { id: 'jog', name: 'Yogyakarta (Kota)', province: 'DI Yogyakarta', latitude: -7.7956, longitude: 110.3695, timezone: 'WIB' },
  { id: 'slm', name: 'Sleman', province: 'DI Yogyakarta', latitude: -7.7167, longitude: 110.3556, timezone: 'WIB' },
  { id: 'btl', name: 'Bantul', province: 'DI Yogyakarta', latitude: -7.8833, longitude: 110.3333, timezone: 'WIB' },
  { id: 'kpn', name: 'Kulon Progo (Wates)', province: 'DI Yogyakarta', latitude: -7.8583, longitude: 110.1583, timezone: 'WIB' },
  { id: 'gnk', name: 'Gunungkidul (Wonosari)', province: 'DI Yogyakarta', latitude: -7.9667, longitude: 110.6, timezone: 'WIB' },

  // --- JAWA TIMUR (Lengkap Kota & Kabupaten) ---
  { id: 'sby', name: 'Surabaya (Kota)', province: 'Jawa Timur', latitude: -7.2575, longitude: 112.7521, timezone: 'WIB' },
  { id: 'sda', name: 'Sidoarjo', province: 'Jawa Timur', latitude: -7.4478, longitude: 112.7183, timezone: 'WIB' },
  { id: 'grs', name: 'Gresik', province: 'Jawa Timur', latitude: -7.1564, longitude: 112.6558, timezone: 'WIB' },
  { id: 'mlg', name: 'Malang (Kota)', province: 'Jawa Timur', latitude: -7.9666, longitude: 112.6326, timezone: 'WIB' },
  { id: 'k-mlg', name: 'Kabupaten Malang (Kepanjen)', province: 'Jawa Timur', latitude: -8.1319, longitude: 112.5714, timezone: 'WIB' },
  { id: 'btu', name: 'Batu (Kota)', province: 'Jawa Timur', latitude: -7.8711, longitude: 112.5272, timezone: 'WIB' },
  { id: 'psn', name: 'Pasuruan (Kota)', province: 'Jawa Timur', latitude: -7.6453, longitude: 112.9075, timezone: 'WIB' },
  { id: 'k-psn', name: 'Kabupaten Pasuruan (Bangil)', province: 'Jawa Timur', latitude: -7.6, longitude: 112.7667, timezone: 'WIB' },
  { id: 'pro', name: 'Probolinggo (Kota)', province: 'Jawa Timur', latitude: -7.7544, longitude: 113.2158, timezone: 'WIB' },
  { id: 'k-pro', name: 'Kabupaten Probolinggo (Kraksaan)', province: 'Jawa Timur', latitude: -7.7611, longitude: 113.4358, timezone: 'WIB' },
  { id: 'mjk', name: 'Mojokerto (Kota)', province: 'Jawa Timur', latitude: -7.4725, longitude: 112.4339, timezone: 'WIB' },
  { id: 'k-mjk', name: 'Kabupaten Mojokerto (Mojosari)', province: 'Jawa Timur', latitude: -7.5256, longitude: 112.5517, timezone: 'WIB' },
  { id: 'jbg', name: 'Jombang', province: 'Jawa Timur', latitude: -7.5461, longitude: 112.2331, timezone: 'WIB' },
  { id: 'kdr', name: 'Kediri (Kota)', province: 'Jawa Timur', latitude: -7.848, longitude: 112.0178, timezone: 'WIB' },
  { id: 'k-kdr', name: 'Kabupaten Kediri (Pare)', province: 'Jawa Timur', latitude: -7.7706, longitude: 112.1953, timezone: 'WIB' },
  { id: 'blt', name: 'Blitar (Kota)', province: 'Jawa Timur', latitude: -8.0983, longitude: 112.1681, timezone: 'WIB' },
  { id: 'k-blt', name: 'Kabupaten Blitar (Kanigoro)', province: 'Jawa Timur', latitude: -8.1306, longitude: 112.2189, timezone: 'WIB' },
  { id: 'mdn-jt', name: 'Madiun (Kota)', province: 'Jawa Timur', latitude: -7.6298, longitude: 111.5239, timezone: 'WIB' },
  { id: 'k-mdn', name: 'Kabupaten Madiun (Caruban)', province: 'Jawa Timur', latitude: -7.5458, longitude: 111.6625, timezone: 'WIB' },
  { id: 'mgt', name: 'Magetan', province: 'Jawa Timur', latitude: -7.6539, longitude: 111.3283, timezone: 'WIB' },
  { id: 'ngw', name: 'Ngawi', province: 'Jawa Timur', latitude: -7.4042, longitude: 111.4456, timezone: 'WIB' },
  { id: 'pnr', name: 'Ponorogo', province: 'Jawa Timur', latitude: -7.8686, longitude: 111.4622, timezone: 'WIB' },
  { id: 'pct', name: 'Pacitan', province: 'Jawa Timur', latitude: -8.2067, longitude: 111.0922, timezone: 'WIB' },
  { id: 'tgk', name: 'Trenggalek', province: 'Jawa Timur', latitude: -8.05, longitude: 111.7167, timezone: 'WIB' },
  { id: 'tlg', name: 'Tulungagung', province: 'Jawa Timur', latitude: -8.0667, longitude: 111.9, timezone: 'WIB' },
  { id: 'ngj', name: 'Nganjuk', province: 'Jawa Timur', latitude: -7.6039, longitude: 111.9039, timezone: 'WIB' },
  { id: 'bjn-jt', name: 'Bojonegoro', province: 'Jawa Timur', latitude: -7.15, longitude: 111.8819, timezone: 'WIB' },
  { id: 'tbn', name: 'Tuban', province: 'Jawa Timur', latitude: -6.8978, longitude: 112.0647, timezone: 'WIB' },
  { id: 'lmg', name: 'Lamongan', province: 'Jawa Timur', latitude: -7.1197, longitude: 112.415, timezone: 'WIB' },
  { id: 'lmj', name: 'Lumajang', province: 'Jawa Timur', latitude: -8.1333, longitude: 113.2222, timezone: 'WIB' },
  { id: 'jmb-jt', name: 'Jember', province: 'Jawa Timur', latitude: -8.1725, longitude: 113.6994, timezone: 'WIB' },
  { id: 'bdw', name: 'Bondowoso', province: 'Jawa Timur', latitude: -7.9133, longitude: 113.8214, timezone: 'WIB' },
  { id: 'stb', name: 'Situbondo', province: 'Jawa Timur', latitude: -7.7064, longitude: 114.0047, timezone: 'WIB' },
  { id: 'byw', name: 'Banyuwangi', province: 'Jawa Timur', latitude: -8.2192, longitude: 114.3692, timezone: 'WIB' },
  { id: 'bkl-mdr', name: 'Bangkalan (Madura)', province: 'Jawa Timur', latitude: -7.0456, longitude: 112.7483, timezone: 'WIB' },
  { id: 'spg-mdr', name: 'Sampang (Madura)', province: 'Jawa Timur', latitude: -7.1878, longitude: 113.2394, timezone: 'WIB' },
  { id: 'pmk-mdr', name: 'Pamekasan (Madura)', province: 'Jawa Timur', latitude: -7.1611, longitude: 113.4756, timezone: 'WIB' },
  { id: 'smn-mdr', name: 'Sumenep (Madura)', province: 'Jawa Timur', latitude: -7.0167, longitude: 113.8667, timezone: 'WIB' },

  // --- SUMATERA & KEPULAUAN ---
  { id: 'bda', name: 'Banda Aceh', province: 'Aceh', latitude: 5.5483, longitude: 95.3238, timezone: 'WIB' },
  { id: 'mdn', name: 'Medan', province: 'Sumatera Utara', latitude: 3.5952, longitude: 98.6722, timezone: 'WIB' },
  { id: 'pdg', name: 'Padang', province: 'Sumatera Barat', latitude: -0.9471, longitude: 100.4172, timezone: 'WIB' },
  { id: 'pku', name: 'Pekanbaru', province: 'Riau', latitude: 0.5071, longitude: 101.4478, timezone: 'WIB' },
  { id: 'btm', name: 'Batam', province: 'Kepulauan Riau', latitude: 1.1301, longitude: 104.0529, timezone: 'WIB' },
  { id: 'tpi', name: 'Tanjung Pinang', province: 'Kepulauan Riau', latitude: 0.9167, longitude: 104.45, timezone: 'WIB' },
  { id: 'jmb', name: 'Jambi', province: 'Jambi', latitude: -1.6101, longitude: 103.6131, timezone: 'WIB' },
  { id: 'bkl', name: 'Bengkulu', province: 'Bengkulu', latitude: -3.8004, longitude: 102.2655, timezone: 'WIB' },
  { id: 'plg', name: 'Palembang', province: 'Sumatera Selatan', latitude: -2.9909, longitude: 104.7565, timezone: 'WIB' },
  { id: 'bdr', name: 'Bandar Lampung', province: 'Lampung', latitude: -5.45, longitude: 105.2667, timezone: 'WIB' },
  { id: 'pkr', name: 'Pangkal Pinang', province: 'Bangka Belitung', latitude: -2.1333, longitude: 106.1167, timezone: 'WIB' },

  // --- BALI & NUSA TENGGARA ---
  { id: 'dps', name: 'Denpasar', province: 'Bali', latitude: -8.6705, longitude: 115.2126, timezone: 'WITA' },
  { id: 'mat', name: 'Mataram (Lombok)', province: 'Nusa Tenggara Barat', latitude: -8.5833, longitude: 116.1167, timezone: 'WITA' },
  { id: 'kpg', name: 'Kupang', province: 'Nusa Tenggara Timur', latitude: -10.1772, longitude: 123.607, timezone: 'WITA' },

  // --- KALIMANTAN ---
  { id: 'ptk', name: 'Pontianak', province: 'Kalimantan Barat', latitude: -0.0263, longitude: 109.3425, timezone: 'WIB' },
  { id: 'bjm', name: 'Banjarmasin', province: 'Kalimantan Selatan', latitude: -3.3194, longitude: 114.5908, timezone: 'WITA' },
  { id: 'plk', name: 'Palangkaraya', province: 'Kalimantan Tengah', latitude: -2.2078, longitude: 113.9167, timezone: 'WIB' },
  { id: 'smr', name: 'Samarinda', province: 'Kalimantan Timur', latitude: -0.5022, longitude: 117.1536, timezone: 'WITA' },
  { id: 'bpp', name: 'Balikpapan', province: 'Kalimantan Timur', latitude: -1.2379, longitude: 116.8289, timezone: 'WITA' },
  { id: 'tjn', name: 'Tanjung Selor', province: 'Kalimantan Utara', latitude: 2.8378, longitude: 117.3653, timezone: 'WITA' },

  // --- SULAWESI ---
  { id: 'mks', name: 'Makassar', province: 'Sulawesi Selatan', latitude: -5.1477, longitude: 119.4327, timezone: 'WITA' },
  { id: 'mnd', name: 'Manado', province: 'Sulawesi Utara', latitude: 1.4748, longitude: 124.8421, timezone: 'WITA' },
  { id: 'plu', name: 'Palu', province: 'Sulawesi Tengah', latitude: -0.8917, longitude: 119.8707, timezone: 'WITA' },
  { id: 'kdr-sl', name: 'Kendari', province: 'Sulawesi Tenggara', latitude: -3.9985, longitude: 122.5126, timezone: 'WITA' },
  { id: 'gto', name: 'Gorontalo', province: 'Gorontalo', latitude: 0.5435, longitude: 123.0568, timezone: 'WITA' },
  { id: 'mmj', name: 'Mamuju', province: 'Sulawesi Barat', latitude: -2.6719, longitude: 118.8878, timezone: 'WITA' },

  // --- MALUKU & PAPUA ---
  { id: 'amb', name: 'Ambon', province: 'Maluku', latitude: -3.6954, longitude: 128.1814, timezone: 'WIT' },
  { id: 'tte', name: 'Ternate', province: 'Maluku Utara', latitude: 0.7833, longitude: 127.3667, timezone: 'WIT' },
  { id: 'jpr', name: 'Jayapura', province: 'Papua', latitude: -2.5337, longitude: 140.7181, timezone: 'WIT' },
  { id: 'mnk', name: 'Manokwari', province: 'Papua Barat', latitude: -0.8615, longitude: 134.062, timezone: 'WIT' },
  { id: 'srg-pp', name: 'Sorong', province: 'Papua Barat Daya', latitude: -0.8667, longitude: 131.25, timezone: 'WIT' },
  { id: 'mrk', name: 'Merauke', province: 'Papua Selatan', latitude: -8.4991, longitude: 140.4047, timezone: 'WIT' },
];
